name: JSON Format

on:
  pull_request_target:
    branches: [format]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.json
        only_changed: True
    - name: Commit changes
      uses: EndBug/add-and-commit@v7